server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

kafka:
  topics:
    order: order.v1
    audit: audit.v1
    product: product.v1

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

pg:
  callback-url: http://localhost:8080/api/v1/payments/callback
  auth:
    client-id: abcd


resilience4j.retry:
  configs:
    default:
      maxAttempts: 1
      waitDuration: 1000
      retryExceptions:
        - java.lang.Throwable
  instances:
    defaultConfig:
      baseConfig: default
    pgRequestPaymentRetryConfig:
      baseConfig: default
      waitDuration: 500

resilience4j:
  circuitbreaker:
    configs:
      default:
        slow-call-rate-threshold: 50
        failure-rate-threshold: 50
        slow-call-duration-threshold: 300
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 500
        sliding-window-type: time_based
        sliding-window-size: 10
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 1000
        event-consumer-buffer-size: 1
        register-health-indicator: true
        record-exceptions:
          - java.lang.Throwable
    instances:
      defaultConfig:
        baseConfig: default
      pgRequestPaymentConfig:
        baseConfig: default
        slow-call-duration-threshold: 200

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false